#!/usr/bin/expect -f

set timeout -1
set ip [lindex $argv 0]
set password [lindex $argv 1]
set src [lindex $argv 2]
set dest [lindex $argv 3]

spawn rsync -av --delete --exclude "node_modules" --exclude ".next" --exclude ".git" --exclude ".env" --exclude "prisma/dev.db" --exclude "public/uploads" "$src" "root@$ip:$dest"

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    eof
}
