#!/usr/bin/expect -f
set ip [lindex $argv 0]
set password [lindex $argv 1]
set command [lindex $argv 2]

set timeout 300

spawn ssh root@$ip $command

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "root@$ip's password:" {
        send "$password\r"
        exp_continue
    }
    "(yes/no)?" {
        send "yes\r"
        exp_continue
    }
    timeout {
        puts "Timeout waiting for response"
        exit 1
    }
    eof
}
